"""Every string our POT carries reaches a reader of Arabic or German.

`onedesk/locale/main.pot` is generated by `bench generate-pot-file --app onedesk`
and carries every label, description, Select option and `_()` string this app
puts on a screen — including the ones whose text frappe, erpnext or hrms already
say somewhere of their own.

Those we leave with an empty `msgstr`. Babel omits an empty entry from the
compiled MO, and `get_translations_from_apps` merges every installed app's
catalogue, so "Salary Slip" resolves from hrms's translation rather than a
second copy of it in ours. What we do translate is our own strings, plus the
handful upstream leaves blank or says in the wrong sense — "Leave" as the verb
where our rail means the noun. Ours wins there because onedesk is installed
last and its MO is merged last.

Which makes this the other half of `docs/WORDING.md`: rewording a label is also
a translation change, and forgetting the second half fails here rather than in
front of somebody reading the form in Arabic.
"""

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
LOCALE = ROOT / "onedesk" / "locale"
BENCH = Path("/home/frappe/bench1/apps")

#: Languages kept complete in the repo.
SHIPPED = ("ar", "de")

#: Whose catalogues a reader of our site also has loaded.
UPSTREAM = ("frappe", "erpnext", "hrms")

ENTRY = re.compile(r"^msgid ((?:\"[^\n]*\"\n)+)msgstr ((?:\"[^\n]*\"\n?)+)", re.M)
QUOTED = re.compile(r"\"((?:[^\"\\]|\\.)*)\"")


def read(path: Path) -> dict[str, str]:
	if not path.exists():
		return {}
	found = {}
	for match in ENTRY.finditer(path.read_text(encoding="utf-8")):
		msgid = "".join(QUOTED.findall(match.group(1)))
		if msgid:
			found[msgid] = "".join(QUOTED.findall(match.group(2)))
	return found


def upstream(lang: str) -> dict[str, str]:
	found = {}
	for app in UPSTREAM:
		for msgid, msgstr in read(BENCH / app / app / "locale" / f"{lang}.po").items():
			if msgstr:
				found.setdefault(msgid, msgstr)
	return found


def test_the_pot_exists():
	assert (LOCALE / "main.pot").exists(), "run bench generate-pot-file --app onedesk"


@pytest.mark.parametrize("lang", SHIPPED)
def test_every_string_reaches_a_reader(lang):
	ours = read(LOCALE / f"{lang}.po")
	theirs = upstream(lang)

	missing = sorted(
		msgid
		for msgid in read(LOCALE / "main.pot")
		if not ours.get(msgid) and not theirs.get(msgid)
	)
	assert not missing, (
		f"{lang}.po leaves these untranslated and no installed app translates them:\n  "
		+ "\n  ".join(missing)
	)


@pytest.mark.parametrize("lang", SHIPPED)
def test_nothing_is_translated_that_is_not_said(lang):
	"""A msgid left behind by a reworded label is a translation nobody reads."""
	pot = read(LOCALE / "main.pot")
	stale = sorted(
		msgid for msgid, msgstr in read(LOCALE / f"{lang}.po").items() if msgstr and msgid not in pot
	)
	assert not stale, f"{lang}.po translates strings no longer in the POT:\n  " + "\n  ".join(stale)


@pytest.mark.parametrize("lang", SHIPPED)
def test_placeholders_survive_translation(lang):
	"""{0} in the English has to be {0} in the translation, or format() raises."""
	wrong = [
		msgid
		for msgid, msgstr in read(LOCALE / f"{lang}.po").items()
		if msgstr and set(re.findall(r"\{\w*\}", msgid)) != set(re.findall(r"\{\w*\}", msgstr))
	]
	assert not wrong, f"{lang}.po loses or invents placeholders in:\n  " + "\n  ".join(wrong)
