"""docs/ is generated. `--check` fails when it is stale.

Nothing here is typed by hand, so nothing here can drift from the code. A fact
worth documenting that this cannot reach is a fact that belongs in a docstring.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import tree

DOCS = tree.ROOT / "docs"

#: Desk records we ship as fixtures. The doctype is the folder name.
DESK_RECORDS = ("workspace", "dock", "desktop_icon", "custom_sidebar", "sidebar", "role")

HEADER = "<!-- generated by scripts/docs.py — do not edit -->\n"


def doctypes() -> dict[str, list[dict]]:
	found: dict[str, list[dict]] = {}
	for path in tree.fixtures():
		if path.parent.parent.name != "doctype" or path.stem != path.parent.name:
			continue
		spec = json.loads(path.read_text())
		module = spec.get("module", "?")
		found.setdefault(module, []).append(
			{
				"name": spec["name"],
				"fields": len(spec.get("fields", [])),
				"child": bool(spec.get("istable")),
				"single": bool(spec.get("issingle")),
				"submittable": bool(spec.get("is_submittable")),
			}
		)
	return found


def desk_records() -> dict[str, list[str]]:
	found: dict[str, list[str]] = {}
	for path in tree.fixtures():
		parts = path.parts
		for kind in DESK_RECORDS:
			if kind in parts:
				found.setdefault(kind, []).append(path.stem)
	return found


def whitelisted() -> list[str]:
	found = []
	for path in tree.python():
		text = path.read_text()
		if "@frappe.whitelist" not in text:
			continue
		lines = text.splitlines()
		for i, line in enumerate(lines):
			if "@frappe.whitelist" not in line:
				continue
			for after in lines[i + 1 : i + 4]:
				if after.lstrip().startswith("def "):
					name = after.split("def ", 1)[1].split("(", 1)[0]
					dotted = str(path.relative_to(tree.ROOT).with_suffix("")).replace("/", ".")
					found.append(f"{dotted}.{name}")
					break
	return sorted(found)


def modules_page() -> str:
	types = doctypes()
	records = desk_records()
	out = [HEADER, "# Modules\n"]
	for module in tree.modules():
		where = tree.module_dir(module)
		out.append(f"\n## {module}\n")
		out.append(f"\n`{where.relative_to(tree.ROOT)}`\n")
		owned = sorted(types.get(module, []), key=lambda d: d["name"])
		if owned:
			out.append("\n| Doctype | Fields | Kind |\n|---|--:|---|\n")
			for d in owned:
				kind = ", ".join(
					k for k, on in
					(("child", d["child"]), ("single", d["single"]), ("submittable", d["submittable"]))
					if on
				) or "document"
				out.append(f"| {d['name']} | {d['fields']} | {kind} |\n")
		else:
			out.append("\nNo doctypes yet.\n")

	out.append("\n## Desk records shipped as fixtures\n")
	if records:
		out.append("\n")
		for kind in sorted(records):
			out.append(f"* **{kind}** — {', '.join(sorted(records[kind]))}\n")
	else:
		out.append("\nNone yet.\n")

	methods = whitelisted()
	out.append("\n## Whitelisted methods\n")
	out.append("\n" + ("".join(f"* `{m}`\n" for m in methods) if methods else "None yet.\n"))
	return "".join(out)


def upstream_page() -> str:
	record = json.loads((tree.ROOT / "upstream.json").read_text())
	out = [HEADER, "# Upstream\n", "\nWhat this app was last read against.\n"]
	out.append(f"\nRecorded {record['recorded_on']}.\n\n")
	out.append("| App | Commit | Dated |\n|---|---|---|\n")
	for app in ("frappe", "erpnext", "hrms"):
		if app in record:
			out.append(f"| {app} | `{record[app]['sha'][:10]}` | {record[app]['date']} |\n")
	out.append("\n`python scripts/upstream.py` says what has landed since.\n")
	return "".join(out)


PAGES = {"MODULES.md": modules_page, "UPSTREAM.md": upstream_page}


def main() -> int:
	args = argparse.ArgumentParser()
	args.add_argument("--check", action="store_true")
	opts = args.parse_args()

	DOCS.mkdir(exist_ok=True)
	stale = []
	for name, build in PAGES.items():
		want = build()
		where = DOCS / name
		if opts.check:
			if not where.exists() or where.read_text() != want:
				stale.append(name)
		else:
			where.write_text(want)

	if opts.check and stale:
		print(f"stale: {', '.join(stale)}. Run `python scripts/docs.py`.")
		return 1
	if not opts.check:
		print(f"wrote {', '.join(PAGES)}")
	return 0


if __name__ == "__main__":
	sys.exit(main())
