"""Everything One does that leans on something frappe, erpnext or hrms owns.

Not a changelog: a changelog goes stale and nothing notices. Each row names the
upstream line it depends on, and `--check` fails when that line is gone, so a
`bench update` that moves it breaks a test instead of a screen.

A row belongs here when our code would still run but stop working if upstream
changed — a CSS rule we outweigh, a class we subclass, a seam we hook, a field
we write. Ordinary use of a documented API does not.

    python scripts/overrides.py           write docs/OVERRIDES.md
    python scripts/overrides.py --check   fail if any upstream line is gone
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import tree

BENCH = Path("/home/frappe/bench1/apps")
HEADER = "<!-- generated by scripts/overrides.py — do not edit -->\n"

#: (what we change, why, our file, the upstream file, the line that must stay)
OVERRIDES = [
	(
		"The icon sprite is kept out of flow, not hidden",
		"a gradient in a `display: none` subtree resolves to nothing, so every One mark drew hollow",
		"onedesk/public/css/desk.css",
		"frappe/frappe/public/js/frappe/desk.js",
		'getElementById("all-symbols")',
	),
	(
		"Marks become sprite symbols",
		"27 Custom Icon rows, ids rewritten per mark so two marks cannot share a gradient",
		"scripts/icons.py",
		"frappe/frappe/core/doctype/custom_icon/custom_icon.py",
		"def to_symbol",
	),
	(
		"Switch Theme offers palette x mode",
		"frappe offers Light, Dark and Automatic; One offers its palettes, and system is a checkbox",
		"onedesk/public/js/theme.js",
		"frappe/frappe/public/js/frappe/ui/theme_switcher.js",
		'size: "large"',
	),
	(
		"The theme dialog is two columns",
		"`.theme-grid` is a flex row sized for three cards; a palette is two",
		"onedesk/public/css/desk.css",
		"frappe/frappe/public/scss/desk/theme_switcher.scss",
		".theme-grid {",
	),
	(
		"One's colour ramp",
		"twelve raw values per mode, which every espresso token is a `var()` onto",
		"onedesk/public/css/theme.css",
		"frappe/frappe/public/css/espresso/colors.css",
		"--gray-50",
	),
	(
		"The rail cannot expand",
		"every row is a product with a mark; the words were 142px of nothing",
		"onedesk/public/js/desk.js",
		"frappe/frappe/public/js/frappe/ui/sidebar/dock.js",
		"toggle_collapsed()",
	),
	(
		"The panel header keeps its mark",
		"`dock.scss` hides it while a rail exists; the rail names the app and the panel names the product",
		"onedesk/public/css/desk.css",
		"frappe/frappe/public/scss/desk/dock.scss",
		".header-logo,",
	),
	(
		"Sidebar rows keep their glyphs",
		"same rule, same reason: the rail's marks are not these rows' marks",
		"onedesk/public/css/desk.css",
		"frappe/frappe/public/scss/desk/dock.scss",
		".sidebar-item-icon {",
	),
	(
		"Framework leaves the apps screen",
		"it is frappe's own administration and everyone who needs it holds System Manager",
		"onedesk/one/boot.py",
		"frappe/frappe/boot.py",
		"on_apps_screen",
	),
	(
		"The site wears One at install",
		"`get_app_logo` reads Website Settings first, then Navbar Settings, then a hook we cannot win",
		"onedesk/one/brand.py",
		"frappe/frappe/core/doctype/navbar_settings/navbar_settings.py",
		"def get_app_logo",
	),
	(
		"Three navbar rows are hidden",
		"Frappe Support, About and erpnext's Delete Demo Data; `sync_table` matches by label, so hiding sticks",
		"onedesk/one/declutter.py",
		"frappe/frappe/core/doctype/navbar_settings/navbar_settings.py",
		"def sync_table",
	),
	(
		"erpnext and hrms checklists are marked complete",
		"they are written in erpnext's voice and open over One's own page",
		"onedesk/one/declutter.py",
		"frappe/frappe/desk/desktop.py",
		"get_onboarding_doc",
	),
	(
		"erpnext and hrms mount on One",
		"a companion has no tile and no rail of its own, so their doctypes open in One's shell even cold",
		"onedesk/one/companions.py",
		"frappe/frappe/desk/doctype/dock/dock.py",
		"def mounted_apps",
	),
	(
		"One's site layer names every rail row",
		"mounting appends 24 of their rows; a saved layer is the whole rail, so ours are named too",
		"onedesk/one/companions.py",
		"frappe/frappe/desk/doctype/dock/dock.py",
		"keep_unnamed=False",
	),
	(
		"The setup wizard's persona slide is replaced",
		"its four required questions were read only by `capture_user_persona`",
		"onedesk/public/js/setup_wizard.js",
		"erpnext/erpnext/public/js/setup_wizard.js",
		"persona",
	),
]


def missing() -> list[str]:
	gone = []
	for what, _why, _ours, where, line in OVERRIDES:
		path = BENCH / where
		if not path.exists():
			gone.append(f"{what}: {where} is not in the checkout")
		elif line not in path.read_text():
			gone.append(f"{what}: {where} no longer contains {line!r}")
	return gone


def page() -> str:
	out = [HEADER, "# What we override, and what it leans on\n"]
	out.append(
		"\nEach row is something that would still run but stop working if upstream moved."
		" `python scripts/overrides.py --check` fails when the line in the last column is"
		" gone, which is the point of the table.\n"
	)
	out.append("\n| What | Why | Ours | Upstream | Must still contain |\n")
	out.append("|---|---|---|---|---|\n")
	for what, why, ours, where, line in OVERRIDES:
		out.append(f"| {what} | {why} | `{ours}` | `{where}` | `{line}` |\n")
	out.append(f"\n{len(OVERRIDES)} overrides.\n")
	return "".join(out)


def main() -> int:
	where = tree.ROOT / "docs" / "OVERRIDES.md"
	if "--check" in sys.argv:
		gone = missing()
		if gone:
			print("upstream moved under us:\n  " + "\n  ".join(gone))
			return 1
		want = page()
		if not where.exists() or where.read_text() != want:
			print("docs/OVERRIDES.md is stale. Run `python scripts/overrides.py`.")
			return 1
		return 0
	where.write_text(page())
	print(f"wrote {where.relative_to(tree.ROOT)} ({len(OVERRIDES)} overrides)")
	return 0


if __name__ == "__main__":
	sys.exit(main())
