"""Everything One does that leans on something frappe, erpnext or hrms owns.

Not a changelog: a changelog goes stale and nothing notices. Each row names the
upstream line it depends on, and `--check` fails when that line is gone, so a
`bench update` that moves it breaks a test instead of a screen.

A row belongs here when our code would still run but stop working if upstream
changed — a CSS rule we outweigh, a class we subclass, a seam we hook, a field
we write. Ordinary use of a documented API does not.

    python scripts/overrides.py           write docs/OVERRIDES.md
    python scripts/overrides.py --check   fail if any upstream line is gone
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import tree

BENCH = Path("/home/frappe/bench1/apps")
HEADER = "<!-- generated by scripts/overrides.py — do not edit -->\n"

#: (what we change, why, our file, the upstream file, the line that must stay)
OVERRIDES = [
	(
		"The icon sprite is kept out of flow, not hidden",
		"a gradient in a `display: none` subtree resolves to nothing, so every One mark drew hollow",
		"onedesk/public/css/desk.css",
		"frappe/frappe/public/js/frappe/desk.js",
		'getElementById("all-symbols")',
	),
	(
		"Marks become sprite symbols",
		"27 Custom Icon rows, ids rewritten per mark so two marks cannot share a gradient",
		"scripts/icons.py",
		"frappe/frappe/core/doctype/custom_icon/custom_icon.py",
		"def to_symbol",
	),
	(
		"Switch Theme offers palette x mode",
		"frappe offers Light, Dark and Automatic; One offers its palettes, and system is a checkbox",
		"onedesk/public/js/theme.js",
		"frappe/frappe/public/js/frappe/ui/theme_switcher.js",
		'size: "large"',
	),
	(
		"The theme dialog is two columns",
		"`.theme-grid` is a flex row sized for three cards; a palette is two",
		"onedesk/public/css/desk.css",
		"frappe/frappe/public/scss/desk/theme_switcher.scss",
		".theme-grid {",
	),
	(
		"One's colour ramp",
		"twelve raw values per mode, which every espresso token is a `var()` onto",
		"onedesk/public/css/theme.css",
		"frappe/frappe/public/css/espresso/colors.css",
		"--gray-50",
	),
	(
		"The rail cannot expand",
		"every row is a product with a mark; the words were 142px of nothing",
		"onedesk/public/js/desk.js",
		"frappe/frappe/public/js/frappe/ui/sidebar/dock.js",
		"toggle_collapsed()",
	),
	(
		"The panel header keeps its mark",
		"`dock.scss` hides it while a rail exists; the rail names the app and the panel names the product",
		"onedesk/public/css/desk.css",
		"frappe/frappe/public/scss/desk/dock.scss",
		".header-logo,",
	),
	(
		"Sidebar rows keep their glyphs",
		"same rule, same reason: the rail's marks are not these rows' marks",
		"onedesk/public/css/desk.css",
		"frappe/frappe/public/scss/desk/dock.scss",
		".sidebar-item-icon {",
	),
	(
		"The panel is a column, not a flyout",
		"frappe closes it on every load wherever there is a rail; One is worked inside all day",
		"onedesk/public/js/desk.js",
		"frappe/frappe/public/js/frappe/ui/sidebar/sidebar.js",
		"panel_can_close()",
	),
	(
		"A permanent panel is in flow",
		"out of flow it covers the page, which is right for something summoned and wrong for a column",
		"onedesk/public/css/desk.css",
		"frappe/frappe/public/scss/desk/dock.scss",
		"body.dock-active .body-sidebar {",
	),
	(
		"The Employee band is not a notice",
		"`set_headline` paints its band for an alert; this one is a permanent summary",
		"onedesk/public/css/desk.css",
		"frappe/frappe/public/js/frappe/form/layout.js",
		"form-message border-bottom",
	),
	(
		"Framework leaves the apps screen",
		"it is frappe's own administration and everyone who needs it holds System Manager",
		"onedesk/one/boot.py",
		"frappe/frappe/boot.py",
		"on_apps_screen",
	),
	(
		"The site wears One at install",
		"`get_app_logo` reads Website Settings first, then Navbar Settings, then a hook we cannot win",
		"onedesk/one/brand.py",
		"frappe/frappe/core/doctype/navbar_settings/navbar_settings.py",
		"def get_app_logo",
	),
	(
		"Three navbar rows are hidden",
		"Frappe Support, About and erpnext's Delete Demo Data; `sync_table` matches by label, so hiding sticks",
		"onedesk/one/declutter.py",
		"frappe/frappe/core/doctype/navbar_settings/navbar_settings.py",
		"def sync_table",
	),
	(
		"erpnext and hrms checklists are marked complete",
		"they are written in erpnext's voice and open over One's own page",
		"onedesk/one/declutter.py",
		"frappe/frappe/desk/desktop.py",
		"get_onboarding_doc",
	),
	(
		"erpnext and hrms mount on One",
		"a companion has no tile and no rail of its own, so their doctypes open in One's shell even cold",
		"onedesk/one/companions.py",
		"frappe/frappe/desk/doctype/dock/dock.py",
		"def mounted_apps",
	),
	(
		"One's site layer names every rail row",
		"mounting appends 24 of their rows; a saved layer is the whole rail, so ours are named too",
		"onedesk/one/companions.py",
		"frappe/frappe/desk/doctype/dock/dock.py",
		"keep_unnamed=False",
	),
	(
		"Employee's fields are reordered",
		"a `field_order` property setter is the only lever that moves a standard field between tabs",
		"onedesk/one_hr/custom/employee.json",
		"frappe/frappe/model/meta.py",
		"`field_order` property setter",
	),
	(
		"The Approvers section rides the holiday list",
		"hrms hangs Default Shift and all three approvers off `holiday_list`, which it then hides",
		"onedesk/one_hr/custom/employee.json",
		"hrms/hrms/setup.py",
		'"insert_after": "default_shift"',
	),
	(
		"Every shift location counts, not the first",
		"they collect all of them and then check `[0]`, so a depot and four sites share one fence",
		"onedesk/one_hr/checkin.py",
		"hrms/hrms/hr/doctype/employee_checkin/employee_checkin.py",
		"def validate_distance_from_shift_location",
	),
	(
		"A gated clock-in is not re-judged on distance",
		"a workspace that says network *or* place has settled it; checking again overrules its own setting",
		"onedesk/one_hr/checkin.py",
		"hrms/hrms/hr/doctype/employee_checkin/employee_checkin.py",
		"CheckinRadiusExceededError",
	),
	(
		"The rail carries a clock-in control",
		"`get_shortcuts` is the documented list; One already subclasses Dock to keep the rail collapsed",
		"onedesk/public/js/desk.js",
		"frappe/frappe/public/js/frappe/ui/sidebar/dock.js",
		"get_shortcuts()",
	),
	(
		"The reason on an Attendance Request is a record",
		"their status mapping compares `self.reason` to one literal string, so ours writes that field",
		"onedesk/one_hr/request.py",
		"hrms/hrms/hr/doctype/attendance_request/attendance_request.py",
		'elif self.reason == "Work From Home":',
	),
	(
		"Submitting an Attendance Request is signed, and turning one down is a verb",
		"their whole approval is that Employee has no submit grant; nothing records who decided or said no",
		"onedesk/one_hr/request.py",
		"hrms/hrms/hr/doctype/attendance_request/attendance_request.py",
		"def on_submit",
	),
	(
		"Every Company field is hidden",
		"One workspace is one company, so two hundred-odd mandatory Links show the same value",
		"onedesk/one/company.py",
		"frappe/frappe/custom/doctype/property_setter/property_setter.py",
		"def make_property_setter",
	),
	(
		"A shift request says what approving it will do",
		"their `show_submit_message` writes a generic line into the one message area after refresh",
		"onedesk/public/js/decision.js",
		"frappe/frappe/public/js/frappe/form/form.js",
		"Submit this document to confirm",
	),
	(
		"Submitting a Shift Request is signed, and the status is set by the buttons",
		"their `on_submit` refuses while the status is Draft, a rule the toolbar button does not carry",
		"onedesk/one_hr/shift.py",
		"hrms/hrms/hr/doctype/shift_request/shift_request.py",
		"Only Shift Request with status 'Approved' and 'Rejected' can be submitted",
	),
	(
		"The Approver field fills itself, or says nobody can",
		"mandatory, and valid only against the employee's own approver and their department's rows",
		"onedesk/one_hr/shift.py",
		"hrms/hrms/hr/doctype/shift_request/shift_request.py",
		"def validate_approver",
	),
	(
		"Reading attendance into an Overtime Slip does not save the slip",
		"their Fetch ends in `self.save()`, so it inserted a record and left the person on a blank form",
		"onedesk/one_hr/overtime.py",
		"hrms/hrms/hr/doctype/overtime_slip/overtime_slip.py",
		"def get_emp_and_overtime_details",
	),
	(
		"An Overtime Slip's dates come from the frequency or the calendar month",
		"theirs threw for anybody without a salary structure, naming the date it was working out",
		"onedesk/public/js/overtime_slip.js",
		"hrms/hrms/hr/doctype/overtime_slip/overtime_slip.js",
		"set_frequency_and_dates",
	),
	(
		"A form event handler of the same name replaces theirs",
		"`frm.events[fieldname]` keeps the last registered handler, and doctype_js loads after the doctype's own",
		"onedesk/public/js/overtime_slip.js",
		"frappe/frappe/public/js/frappe/form/script_manager.js",
		"cur_frm.events[fieldname] = _handler",
	),
	(
		"An Overtime Slip says what it will pay before it is submitted",
		"the figure is theirs, from the method `on_submit` uses, rather than a second copy of the arithmetic",
		"onedesk/one_hr/overtime.py",
		"hrms/hrms/hr/doctype/overtime_slip/overtime_slip.py",
		"def get_overtime_component_amounts",
	),
	(
		"The timesheet timer is ours",
		"theirs resumes any row with Completed unticked and overwrites the end time that was already there",
		"onedesk/public/js/timesheet.js",
		"erpnext/erpnext/projects/doctype/timesheet/timesheet.js",
		"Resume Timer",
	),
	(
		"The timer stamps one clock",
		"theirs writes `get_datetime_as_string()` (the operator's machine) and measures against the site's timezone",
		"onedesk/public/js/timesheet.js",
		"erpnext/erpnext/public/js/projects/timer.js",
		"grid_row.doc.to_time = frappe.datetime.get_datetime_as_string()",
	),
	(
		"Monthly Attendance is one row per person, and everybody is on it",
		"theirs keys on employee and shift, and skips anybody with no Attendance row at all",
		"onedesk/one_hr/report/monthly_attendance/monthly_attendance.py",
		"hrms/hrms/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py",
		"if not employee_attendance:",
	),
	(
		"The month sheet is built from their pieces rather than re-implemented",
		"their attendance map, holiday map and status abbreviations decide what a day means; we only reshape",
		"onedesk/one_hr/report/monthly_attendance/monthly_attendance.py",
		"hrms/hrms/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py",
		"def set_defaults_for_summarized_view",
	),
	(
		"Attendance by Shift keeps every day in the period",
		"their two inner joins dropped 26 of 27 days silently, so every count had lost its denominator",
		"onedesk/one_hr/report/attendance_by_shift/attendance_by_shift.py",
		"hrms/hrms/hr/report/shift_attendance/shift_attendance.py",
		".inner_join(shift_type)",
	),
	(
		"The grace-period arithmetic on a shift day is theirs",
		"late and early are measured against the shift window their own helpers know how to read",
		"onedesk/one_hr/report/attendance_by_shift/attendance_by_shift.py",
		"hrms/hrms/hr/report/shift_attendance/shift_attendance.py",
		"def update_late_entry",
	),
	(
		"An onboarding takes the company's holiday list",
		"an onboarding is for somebody who is not an employee yet, so their branch throws on a field nothing fills",
		"onedesk/one_hr/lifecycle.py",
		"hrms/hrms/controllers/employee_boarding_controller.py",
		"def get_holiday_list",
	),
	(
		"A boarding project starts no later than its first activity",
		"theirs starts the project on the joining date while the tasks start from boarding_begins_on, and erpnext's own Task guard then refuses the first one",
		"onedesk/one_hr/lifecycle.py",
		"hrms/hrms/controllers/employee_boarding_controller.py",
		"\"expected_start_date\": self.date_of_joining",
	),
	(
		"An appraisal carries its cycle's dates",
		"their own duplicate check compares start_date and end_date, and nothing in hrms ever fills either, so only the same-cycle branch can fire",
		"onedesk/one_hr/growth.py",
		"hrms/hrms/hr/doctype/appraisal/appraisal.py",
		"def validate_duplicate",
	),
	(
		"A cycle with appraisals on it is In Progress",
		"nothing in hrms sets that status, and the cycle summary looks its subject up by it",
		"onedesk/one_hr/growth.py",
		"hrms/hrms/hr/doctype/appraisal_cycle/appraisal_cycle.py",
		"def get_employees_without_feedback",
	),
	(
		"Hiring is measured from the opening, not from a staffing plan",
		"theirs walks Staffing Plan to Job Opening, so an opening with no plan on it has no applicants, no interviews and no offers in the report at all",
		"onedesk/one_hr/report/hiring_pipeline/hiring_pipeline.py",
		"hrms/hrms/hr/report/recruitment_analytics/recruitment_analytics.py",
		"staffing_plan_details = get_staffing_plan(filters)",
	),
	(
		"Available hours are working days, not calendar days",
		"theirs multiplied the standard day by every date in the range, weekends and holidays included",
		"onedesk/one_hr/report/hours_utilization/hours_utilization.py",
		"hrms/hrms/hr/report/employee_hours_utilization_based_on_timesheet/employee_hours_utilization_based_on_timesheet.py",
		"self.standard_working_hours * self.day_span",
	),
	(
		"Hours Utilization counts submitted timesheets and lists everybody",
		"theirs had no docstatus filter, and built its rows from the logs so nobody at nought appeared",
		"onedesk/one_hr/report/hours_utilization/hours_utilization.py",
		"hrms/hrms/hr/report/employee_hours_utilization_based_on_timesheet/employee_hours_utilization_based_on_timesheet.py",
		"def generate_stats_by_employee",
	),
	(
		"No report asks which company",
		"a report's filters are a list in its own script, so the doctype sweep could not reach them",
		"onedesk/public/js/reports.js",
		"frappe/frappe/public/js/frappe/views/reports/query_report.js",
		"setup_filters() {",
	),
	(
		"A report is called what the rail called it",
		"the heading is the report's own name; `page_title` is set and nothing reads it",
		"onedesk/public/js/reports.js",
		"frappe/frappe/public/js/frappe/views/reports/query_report.js",
		"set_breadcrumbs() {",
	),
	(
		"A leave application is answered, and the answer is signed",
		"their `on_submit` throws unless the Status dropdown was set first, which the toolbar does not know",
		"onedesk/one_hr/leave.py",
		"hrms/hrms/hr/doctype/leave_application/leave_application.py",
		"Only Leave Applications with status 'Approved' and 'Rejected' can be submitted",
	),
	(
		"The balance in the headline is worked out, not read",
		"`leave_balance` is filled by their form script, so it is nought on an application made any other way",
		"onedesk/one_hr/leave.py",
		"hrms/hrms/hr/doctype/leave_application/leave_application.py",
		"def get_leave_balance_on",
	),
	(
		"Telemetry bookkeeping is kept off the screen",
		"their milestone insert fails inside a savepoint and the message outlives the rollback",
		"onedesk/one/quiet.py",
		"hrms/hrms/telemetry.py",
		"def _claim_milestone",
	),
	(
		"The two leave mails have something to send",
		"`send_leave_notification` ships on with no template, so every approval nagged instead",
		"onedesk/fixtures/email_template.json",
		"hrms/hrms/hr/doctype/leave_application/leave_application.py",
		"Please set default template for Leave Status Notification in HR Settings.",
	),
	(
		"An appointment letter carries the template it was told to use",
		"`introduction` and `terms` are both required and both filled by eleven lines of their form script",
		"onedesk/one_hr/letter.py",
		"hrms/hrms/hr/doctype/appointment_letter/appointment_letter.py",
		"def get_appointment_letter_details",
	),
	(
		"An interview is titled by the person being interviewed",
		"its title field is the Job Applicant's docname, which hrms names after their email address",
		"onedesk/one_hr/custom/interview.json",
		"hrms/hrms/hr/doctype/job_applicant/job_applicant.py",
		"self.name = self.email_id",
	),
	(
		"A vehicle log says how far, on how much",
		"it carries the last and current odometer and not the distance between them, and hides the litres behind a collapsed section",
		"onedesk/public/js/vehicle_log.js",
		"hrms/hrms/hr/doctype/vehicle_log/vehicle_log.json",
		"last_odometer",
	),
	(
		"The site has a default fiscal year",
		"Vehicle Expenses defaults its filter to a user default nothing sets, then throws in a red modal before the page has drawn",
		"onedesk/one_hr/accounts.py",
		"hrms/hrms/hr/report/vehicle_expenses/vehicle_expenses.js",
		'default: frappe.defaults.get_user_default("fiscal_year")',
	),
	(
		"A report that wants a fiscal year opens on the one we are in",
		"the same answer as the payroll period, for the filter that throws rather than asking",
		"onedesk/public/js/reports.js",
		"erpnext/erpnext/accounts/report/financial_statements.py",
		"Start Year and End Year are mandatory",
	),
	(
		"An employee advance can be made on a site nobody has edited the accounts on",
		"erpnext ships Employee Advances as `account_type: Payable` beside `account_category: Other Receivables`, and hrms demands Receivable",
		"onedesk/one_hr/accounts.py",
		"hrms/hrms/hr/doctype/employee_advance/employee_advance.py",
		"Employee advance account {0} should be of type {1}.",
	),
	(
		"An expense claim is answered, and the answer is signed",
		"its verdict is a Select the approver edits by hand, and `on_submit` throws if they forgot — a rule the Submit button does not carry",
		"onedesk/one_hr/expense.py",
		"hrms/hrms/hr/doctype/expense_claim/expense_claim.py",
		"Approval Status must be 'Approved' or 'Rejected'",
	),
	(
		"Every expense row gets the one cost centre there is",
		"it is required to book the claim and filled only by their form script, from the claim, from the company",
		"onedesk/one_hr/expense.py",
		"hrms/hrms/hr/doctype/expense_claim/expense_claim.js",
		"set_child_cost_center: function (frm) {",
	),
	(
		"A benefit application knows its own ceiling",
		"`max_benefits` is filled by a whitelisted method only their form script calls, and validate compares against it",
		"onedesk/one_hr/benefit.py",
		"hrms/hrms/payroll/doctype/employee_benefit_application/employee_benefit_application.py",
		"def set_benefit_components_and_currency",
	),
	(
		"A benefit application adds up its own table",
		"`total_amount` and `remaining_benefit` are computed in their form script and nowhere on the server",
		"onedesk/one_hr/benefit.py",
		"hrms/hrms/payroll/doctype/employee_benefit_application/employee_benefit_application.js",
		"doc.remaining_benefit = doc.max_benefits - total_amount;",
	),
	(
		"A benefit claim knows what is left to claim",
		"`max_amount_eligible` is filled the same way, and validate compares against it",
		"onedesk/one_hr/benefit.py",
		"hrms/hrms/payroll/doctype/employee_benefit_claim/employee_benefit_claim.py",
		"def get_benefit_details",
	),
	(
		"A payroll year exists from the first day",
		"nothing upstream creates a Payroll Period, and a salary slip asks for one the moment a workspace has an Income Tax Slab",
		"onedesk/one/setup_wizard.py",
		"hrms/hrms/payroll/doctype/salary_slip/salary_slip.py",
		"return get_payroll_period(self.start_date, self.end_date, self.company)",
	),
	(
		"A tax report opens on a period rather than a red box",
		"`payroll_period` is required and defaulted to nothing on two reports, and a workspace has one per year",
		"onedesk/public/js/reports.js",
		"hrms/hrms/payroll/report/income_tax_computation/income_tax_computation.js",
		'fieldname: "payroll_period"',
	),
	(
		"The deduction reports open on the last payroll month",
		"their shared filters default the month to whatever month it is today, which is never the month payroll was last run for",
		"onedesk/public/js/reports.js",
		"hrms/hrms/public/js/salary_slip_deductions_report_filters.js",
		"default: frappe.datetime.str_to_obj(frappe.datetime.get_today()).getMonth() + 1,",
	),
	(
		"A tax claim says what was claimed and what is allowed",
		"both screens open on a tab carrying the department and the currency, and put the table and the two totals on the next one",
		"onedesk/public/js/exemption.js",
		"hrms/hrms/payroll/doctype/employee_tax_exemption_declaration/employee_tax_exemption_declaration.json",
		"total_exemption_amount",
	),
	(
		"A dashboard is called what the rail called it",
		"`Dashboard.set_breadcrumbs` sends no label, and the crumb renderer beside it reads one",
		"onedesk/public/js/reports.js",
		"frappe/frappe/core/page/dashboard_view/dashboard_view.js",
		'frappe.breadcrumbs.add({ module: "Desk", doctype: "Dashboard", docname: docname });',
	),
	(
		"A payroll run says how many people and how much",
		"the Overview tab carries the account and two checkboxes; the count is parked in the employee filter and the total is only in the slips",
		"onedesk/public/js/payroll_entry.js",
		"hrms/hrms/payroll/doctype/payroll_entry/payroll_entry.json",
		"number_of_employees",
	),
	(
		"Nobody is asked what currency they are paid in",
		"twenty-two HR and payroll doctypes carry a Currency link; the fourteen nobody types are hidden",
		"onedesk/one_hr/money.py",
		"hrms/hrms/payroll/doctype/salary_slip/salary_slip.json",
		"salary_structure.currency",
	),
	(
		"The salary register opens on the last payroll that was run",
		"it ships a month-ago-to-today range, and its query keeps only slips wholly inside it, so it can never contain a payroll month",
		"onedesk/public/js/reports.js",
		"hrms/hrms/payroll/report/salary_register/salary_register.js",
		'default: frappe.datetime.add_months(frappe.datetime.get_today(), -1)',
	),
	(
		"A payroll run can be made on a site nobody has edited the accounts on",
		"erpnext names Payroll Payable and nominates it, and leaves its `account_type` unset, so every payroll entry is refused",
		"onedesk/one_hr/accounts.py",
		"hrms/hrms/payroll/doctype/payroll_entry/payroll_entry.py",
		"Account type should be set {0} for payroll payable account {1}, please set and try again",
	),
	(
		"A payslip says what it pays, on the tab it opens on",
		"the money is on the third and fourth tabs; the first carries the letter head and the designation",
		"onedesk/public/js/salary_slip.js",
		"hrms/hrms/payroll/doctype/salary_slip/salary_slip.json",
		"rounded_total",
	),
	(
		"An encashable leave type has something to pay with",
		"HRMS ships Casual Leave with `allow_encashment` on and no earning component, and only says so at submit",
		"onedesk/one_hr/leave.py",
		"hrms/hrms/hr/doctype/leave_encashment/leave_encashment.py",
		"Please set Earning Component for Leave type: {0}.",
	),
	(
		"An encashment says why it is worth nothing",
		"the rate is `leave_encashment_amount_per_day` on the structure or the assignment, which nothing fills and nothing asks for",
		"onedesk/one_hr/encashment.py",
		"hrms/hrms/hr/doctype/leave_encashment/leave_encashment.py",
		"leave_encashment_amount_per_day",
	),
	(
		"The leave panel opens with its dates filled",
		"it sets Dates Based On to the leave period and `from_date` to today in the same breath, and the fetch that would fix that only fires on a change",
		"onedesk/public/js/leave_control_panel.js",
		"hrms/hrms/hr/doctype/leave_control_panel/leave_control_panel.js",
		"from_date: frappe.datetime.get_today(),",
	),
	(
		"The leave panel's employee picker has no Company column",
		"the table is a datatable built in their form script rather than fields, so `one/company.py` cannot reach it",
		"onedesk/public/js/leave_control_panel.js",
		"hrms/hrms/hr/doctype/leave_control_panel/leave_control_panel.js",
		"get_employees_datatable_columns()",
	),
	(
		"An employee link reads the person's name",
		"`show_title_field_in_link` is off upstream, so every link read HR-EMP-00004 and erpnext hung a mirror field beside it",
		"onedesk/one_hr/custom/employee.json",
		"frappe/frappe/boot.py",
		'{"show_title_field_in_link": 1}',
	),
	(
		"The Employee Name mirrors are hidden",
		"forty-seven doctypes say the person's name twice once the link says it itself",
		"onedesk/one_hr/names.py",
		"hrms/hrms/hr/doctype/leave_application/leave_application.json",
		"employee.employee_name",
	),
	(
		"A leave year exists from the first day",
		"nothing upstream creates a Leave Period, and `Employee Leave Balance` dies in its own `onload` without one",
		"onedesk/one/setup_wizard.py",
		"hrms/hrms/hr/report/employee_leave_balance/employee_leave_balance.js",
		"data.message[0].from_date",
	),
	(
		"Total Leaves Allocated is read-only",
		"it is computed on save from the new days plus what was carried forward, so typing in it is overwritten",
		"onedesk/one_hr/custom/leave_allocation.json",
		"hrms/hrms/hr/doctype/leave_allocation/leave_allocation.py",
		"def set_total_leaves_allocated",
	),
	(
		"The setup wizard's persona slide is replaced",
		"its four required questions were read only by `capture_user_persona`",
		"onedesk/public/js/setup_wizard.js",
		"erpnext/erpnext/public/js/setup_wizard.js",
		"persona",
	),
	(
		"The daily job that reopens converted and lost deals is stopped",
		"it sets status Open on any lead or opportunity with an Event today, whatever the status was",
		"onedesk/one_crm/stages.py",
		"erpnext/erpnext/crm/utils.py",
		"def open_leads_opportunities_based_on_todays_event",
	),
	(
		"A stage follows a quotation lost or ordered",
		"the quotation writes the opportunity's status with `db_set`, so no hook of the opportunity's runs",
		"onedesk/one_crm/stages.py",
		"erpnext/erpnext/selling/doctype/quotation/quotation.py",
		"opp.set_status(status=status, update=True)",
	),
	(
		"A stage follows a sales order",
		"the order writes the opportunity's status with `frappe.db.set_value`, past every hook",
		"onedesk/one_crm/stages.py",
		"erpnext/erpnext/selling/doctype/sales_order/sales_order.py",
		'frappe.db.set_value("Opportunity", opportunity_name, "status", flag)',
	),
	(
		"Picking a Lost stage opens Declare Lost",
		"the dialog that asks why is erpnext's, triggered by name",
		"onedesk/public/js/opportunity.js",
		"erpnext/erpnext/public/js/utils/sales_common.js",
		"set_as_lost_dialog: function (frm)",
	),
	(
		"The pipeline board is made on a Link field",
		"only the New Board dialog insists on a Select; the server groups and sets whatever the field is",
		"onedesk/one_crm/board.py",
		"frappe/frappe/desk/doctype/kanban_board/kanban_board.py",
		"frappe.set_value(doctype, docname, fieldname, to_colname)",
	),
	(
		"A pipeline column says what it is worth",
		"painted under the column header, found by the column's value, whenever the count badge is redrawn",
		"onedesk/public/js/opportunity_list.js",
		"frappe/frappe/public/js/frappe/views/kanban/kanban_column.html",
		'data-column-value="{{title}}"',
	),
	(
		"The pipeline's worth is found by route, not onload",
		"the Kanban view overrides setup_view and never calls a list's onload or refresh",
		"onedesk/public/js/opportunity_list.js",
		"frappe/frappe/public/js/frappe/views/kanban/kanban_view.js",
		"this.setup_kanban_board_realtime();",
	),
	(
		"A deal's company-currency value is worked out on the server",
		"erpnext sets base_opportunity_amount only in the form script, so an imported deal is worth nothing",
		"onedesk/one_crm/deal.py",
		"erpnext/erpnext/crm/doctype/opportunity/opportunity.js",
		'"base_opportunity_amount",',
	),
	(
		"A next step's reminder goes to the record's owner",
		"a Reminder takes its user from the session in validate, so the owner is written after insert",
		"onedesk/one_crm/next.py",
		"frappe/frappe/automation/doctype/reminder/reminder.py",
		"self.user = frappe.session.user",
	),
	(
		"Home counts the reader's own deals and leads",
		"a shortcut's stats_filter is evaluated as a JavaScript expression, so it can name frappe.session.user",
		"onedesk/one_crm/workspace/onecrm/onecrm.json",
		"frappe/frappe/public/js/frappe/utils/utils.js",
		"new Function(`return ${filter}`)()",
	),
	(
		"A lead's and a deal's comment box is shown again",
		"erpnext hides it with an inline style when it moves the timeline into Activities; notes are comments now",
		"onedesk/public/css/desk.css",
		"erpnext/erpnext/public/js/utils/crm_activities.js",
		'$(".comment-box").hide();',
	),
	(
		"A call logged by hand owes nobody a popup",
		"Call Log rings the scheduled employees on insert; the logged instance's trigger_call_popup is a no-op",
		"onedesk/one_crm/record.py",
		"erpnext/erpnext/telephony/doctype/call_log/call_log.py",
		"def trigger_call_popup(self):",
	),
	(
		"Mail from a known lead is added to that lead",
		"the receiver looks the sender up only when the insert raises DuplicateEntryError, so capture.py raises that",
		"onedesk/one_crm/capture.py",
		"frappe/frappe/email/receive.py",
		"except frappe.DuplicateEntryError:",
	),
	(
		"A web form's lead is marked, not refused",
		"frappe sets in_web_form while it accepts a submission; a visitor cannot be told they already exist",
		"onedesk/one_crm/capture.py",
		"frappe/frappe/website/doctype/web_form/web_form.py",
		"frappe.flags.in_web_form = True",
	),
	(
		"ERPNext's refusal of a second lead with one email is switched off",
		"it refused the web form and the inbox too; capture.py decides instead",
		"onedesk/one_crm/capture.py",
		"erpnext/erpnext/crm/doctype/lead/lead.py",
		'"allow_lead_duplication_based_on_emails"',
	),
	(
		"A new lead or deal with one series does not show it",
		"erpnext's toggle_naming_series shows Series on every new record, over its property setters",
		"onedesk/public/js/crm_record.js",
		"erpnext/erpnext/public/js/utils.js",
		'cur_frm.toggle_display("naming_series", cur_frm.doc.__islocal ? true : false);',
	),
	(
		"A deal has no Close button",
		"Close is neither won nor lost, so a closed deal stayed in an open stage and out of every total",
		"onedesk/public/js/opportunity.js",
		"erpnext/erpnext/crm/doctype/opportunity/opportunity.js",
		'frm.add_custom_button(__("Close"), function () {',
	),
	(
		"The Source section is shown by saving Selling Settings",
		"its enable_utm switch writes the property setters that hide or show the section on every doctype",
		"onedesk/one_crm/capture.py",
		"erpnext/erpnext/selling/doctype/selling_settings/selling_settings.py",
		"toggle_utm_analytics_section(not self.enable_utm)",
	),
	(
		"Every desk user keeps tasks, and sees only their own and, by role, project tasks",
		"erpnext gives Task to Projects User alone; the grant is a Custom DocPerm and a controller hook narrows it, since a hook cannot grant",
		"onedesk/one_task/access.py",
		"frappe/frappe/permissions.py",
		"if not has_controller_permissions(doc, ptype, user=user, debug=debug):",
	),
	(
		"A to-do about nothing becomes a task, and its ToDo the assignment on it",
		"`new_todo` and the ToDo form make a ToDo with no reference; saving one with a reference is what writes the task's `_assign`",
		"onedesk/one_task/capture.py",
		"frappe/frappe/desk/doctype/todo/todo.py",
		"def update_in_reference(self):",
	),
	(
		"The last assignment ticked off completes a task in no project",
		"the other direction is theirs: a completed task closes its assignments, which is also what stops ours looping",
		"onedesk/one_task/capture.py",
		"erpnext/erpnext/projects/doctype/task/task.py",
		"close_all_assignments(self.doctype, self.name)",
	),
	(
		"Overdue is a date, not a status",
		"their daily job rewrites every open task past its date to Overdue, so a Working card changed columns overnight; the job is stopped and the option dropped",
		"onedesk/one_project/board.py",
		"erpnext/erpnext/hooks.py",
		"erpnext.projects.doctype.task.task.set_tasks_as_overdue",
	),
	(
		"A project's board is theirs, shaped as it is made",
		"their button makes a board per project with a column per status; ours archives Template and Cancelled and sets what a card shows",
		"onedesk/one_project/board.py",
		"erpnext/erpnext/projects/doctype/project/project.py",
		'quick_kanban_board("Task", project.project_name, "status", project.name)',
	),
	(
		"The board is a button of its own on a project",
		"theirs is the second entry under View; ours removes it by label and adds Board beside Actions",
		"onedesk/public/js/project.js",
		"erpnext/erpnext/projects/doctype/project/project.js",
		'__("Kanban Board"),',
	),
	(
		"A task's due date reads as a day on every list and card",
		"Expected End Date is a Datetime; the board draws a card through frappe.format, which reads a docfield's own formatter first",
		"onedesk/public/js/task_list.js",
		"frappe/frappe/public/js/frappe/form/formatters.js",
		"var formatter = df.formatter || frappe.form.get_formatter(fieldtype);",
	),
	(
		"A sub-task's parent becomes a group",
		"they refuse a parent task not marked Is Group, a box nobody ticks before wanting a sub-task",
		"onedesk/one_task/task.py",
		"erpnext/erpnext/projects/doctype/task/task.py",
		"ParentIsGroupError,",
	),
	(
		"A task's timer is a row on the person's timesheet for the week",
		"the task's Actual Time is theirs, filled from timesheets when one is submitted, so a timed hour reaches the task at the week's submit",
		"onedesk/one_task/timer.py",
		"erpnext/erpnext/projects/doctype/timesheet/timesheet.py",
		"def update_task_and_project",
	),
	(
		"A dependency says which project it is in",
		"their slip finds a task's dependants by the project on each Task Depends On row, a read-only field nothing of theirs writes, so it never found any",
		"onedesk/one_project/plan.py",
		"erpnext/erpnext/projects/doctype/task/task.py",
		'filters={"task": self.name, "project": self.project},',
	),
	(
		"A repeating task is due the day it repeats and still to do",
		"Auto Repeat copies the task whole, old dates, Completed and ticked steps included, then runs the copy's on_recurring",
		"onedesk/one_task/task.py",
		"frappe/frappe/automation/doctype/auto_repeat/auto_repeat.py",
		'new_doc.run_method("on_recurring"',
	),
]


def missing() -> list[str]:
	gone = []
	for what, _why, _ours, where, line in OVERRIDES:
		path = BENCH / where
		if not path.exists():
			gone.append(f"{what}: {where} is not in the checkout")
		elif line not in path.read_text():
			gone.append(f"{what}: {where} no longer contains {line!r}")
	return gone


def page() -> str:
	out = [HEADER, "# What we override, and what it leans on\n"]
	out.append(
		"\nEach row is something that would still run but stop working if upstream moved."
		" `python scripts/overrides.py --check` fails when the line in the last column is"
		" gone, which is the point of the table.\n"
	)
	out.append("\n| What | Why | Ours | Upstream | Must still contain |\n")
	out.append("|---|---|---|---|---|\n")
	for what, why, ours, where, line in OVERRIDES:
		out.append(f"| {what} | {why} | `{ours}` | `{where}` | `{line}` |\n")
	out.append(f"\n{len(OVERRIDES)} overrides.\n")
	return "".join(out)


def main() -> int:
	where = tree.ROOT / "docs" / "OVERRIDES.md"
	if "--check" in sys.argv:
		gone = missing()
		if gone:
			print("upstream moved under us:\n  " + "\n  ".join(gone))
			return 1
		want = page()
		if not where.exists() or where.read_text() != want:
			print("docs/OVERRIDES.md is stale. Run `python scripts/overrides.py`.")
			return 1
		return 0
	where.write_text(page())
	print(f"wrote {where.relative_to(tree.ROOT)} ({len(OVERRIDES)} overrides)")
	return 0


if __name__ == "__main__":
	sys.exit(main())
