"""What the framework already gives us, read out of the checkouts.

Generated, and pinned to the shas in upstream.json, so it describes the frappe
we actually have rather than the one somebody remembered. `docs/FRAMEWORK.md`
is the answer to "what do I call instead of writing my own".
"""

import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import tree

BENCH = Path("/home/frappe/bench1/apps")
FRAPPE = BENCH / "frappe"
DESK_JS = FRAPPE / "frappe/public/js"
TOKENS_CSS = FRAPPE / "frappe/public/css/espresso"
UI_PKG = FRAPPE / "ui/package.json"

HEADER = "<!-- generated by scripts/reference.py — do not edit -->\n"


def _grep(pattern: str, where: Path, *, files: str = "") -> list[str]:
	cmd = ["grep", "-rhoP", pattern, str(where)]
	if files:
		cmd.insert(1, f"--include={files}")
	out = subprocess.run(cmd, capture_output=True, text=True)
	return sorted(set(line for line in out.stdout.splitlines() if line))


def namespaces() -> list[str]:
	found = _grep(r"frappe\.provide\(\s*['\"]\K[\w.]+", DESK_JS)
	return [n for n in found if not n.endswith(".") and not n.startswith("frappe._")]


def ui_classes() -> list[str]:
	return _grep(r"frappe\.ui\.\K\w+(?=\s*=\s*class)", DESK_JS)


def top_level() -> list[str]:
	names = _grep(r"^\s*frappe\.\K\w+(?=\s*=\s*(function|\(|async))", DESK_JS)
	return [n for n in names if not n.startswith("_")]


def utils() -> list[str]:
	text = (DESK_JS / "frappe/utils/utils.js").read_text()
	block = text.partition("Object.assign(frappe.utils, {")[2]
	return sorted(set(re.findall(r"^\t(\w+)[(:]", block, re.M)))


def tokens() -> dict[str, dict[str, list[str]]]:
	"""Grouped by family — colors.css alone declares over a thousand."""
	found: dict[str, dict[str, list[str]]] = {}
	for path in sorted(TOKENS_CSS.glob("*.css")):
		names = sorted(set(re.findall(r"^\s*--([\w-]+)\s*:", path.read_text(), re.M)))
		if not names:
			continue
		families: dict[str, list[str]] = {}
		for name in names:
			families.setdefault(name.split("-")[0], []).append(name)
		found[path.stem] = families
	return found


def framework_ui() -> list[str]:
	if not UI_PKG.exists():
		return []
	exports = json.loads(UI_PKG.read_text()).get("exports", {})
	return sorted(k for k in exports if k not in (".", "./*"))


def server_methods() -> dict[str, int]:
	counts: dict[str, int] = {}
	for app in ("frappe", "erpnext", "hrms"):
		where = BENCH / app
		if not where.exists():
			continue
		out = subprocess.run(
			["grep", "-rlc", "@frappe.whitelist", str(where), "--include=*.py"],
			capture_output=True,
			text=True,
		)
		counts[app] = len(out.stdout.splitlines())
	return counts


def page_entry_points() -> list[tuple[str, str]]:
	"""How a page gets onto the desk. Checked against the tree, not recalled."""
	found = []
	if (DESK_JS / "frappe/ui/island/index.js").exists():
		found.append(("frappe.ui.mount_island(el, name, props)", "mount a Vue island in a desk page"))
	if (FRAPPE / "frappe/utils/island.py").exists():
		found.append(("frappe.utils.island.get_island_assets", "resolve an island's module and styles"))
	if (DESK_JS / "frappe/views/workspace").exists():
		found.append(("Workspace", "a page built from links, shortcuts, charts and cards"))
	pages = FRAPPE / "frappe/desk/page"
	if pages.is_dir():
		found.append((f"frappe/desk/page/* ({len(list(pages.iterdir()))} pages)", "the classic desk page"))
	return found


def page() -> str:
	record = json.loads((tree.ROOT / "upstream.json").read_text())
	sha = record.get("frappe", {}).get("sha", "?")[:10]

	out = [HEADER, "# What the framework gives us\n"]
	out.append(f"\nRead out of `frappe` at `{sha}`. Regenerate with `python scripts/reference.py`.\n")
	out.append("\nReach for something here before writing your own. If nothing fits, say so in a line.\n")

	out.append("\n## Mounting a page\n\n")
	for call, what in page_entry_points():
		out.append(f"* `{call}` — {what}\n")

	out.append("\n## `@framework/ui` — the shared Vue components\n\n")
	ui = framework_ui()
	out.append("".join(f"* `@framework/ui{name[1:]}`\n" for name in ui) if ui else "Not in this checkout.\n")

	out.append("\n## The `frappe` client object\n")
	out.append("\n### Namespaces\n\n")
	out.append("".join(f"* `{n}`\n" for n in namespaces()))

	out.append("\n### Called directly\n\n")
	out.append(_columns(f"frappe.{n}" for n in top_level()))

	out.append("\n### `frappe.utils`\n\n")
	out.append(_columns(f"frappe.utils.{n}" for n in utils()))

	out.append("\n### `frappe.ui` classes\n\n")
	out.append(_columns(f"frappe.ui.{n}" for n in ui_classes()))

	out.append("\n## Design tokens\n")
	out.append(
		"\nCSS custom properties, in `frappe/public/css/espresso/`. Use these, never a"
		" literal colour, radius or size. `legacy` is deprecated — do not reach for it.\n"
	)
	for group, families in tokens().items():
		total = sum(len(v) for v in families.values())
		out.append(f"\n### {group} — {total}\n\n")
		for family, names in sorted(families.items()):
			shown = ", ".join(f"`--{n}`" for n in names[:4])
			more = f" …{len(names) - 4} more" if len(names) > 4 else ""
			out.append(f"* **{family}** ({len(names)}) — {shown}{more}\n")

	out.append("\n## Whitelisted server methods\n\n")
	for app, count in server_methods().items():
		out.append(f"* `{app}` — {count} modules expose at least one\n")
	out.append("\nFind one with `grep -rn '@frappe.whitelist' <app>` before adding an endpoint.\n")
	return "".join(out)


def _columns(names) -> str:
	names = list(names)
	return "".join(f"`{n}`{'' if i == len(names) - 1 else ' · '}" for i, n in enumerate(names)) + "\n"


def main() -> int:
	where = tree.ROOT / "docs" / "FRAMEWORK.md"
	want = page()
	if "--check" in sys.argv:
		if not where.exists() or where.read_text() != want:
			print("docs/FRAMEWORK.md is stale. Run `python scripts/reference.py`.")
			return 1
		return 0
	where.write_text(want)
	print(f"wrote {where.relative_to(tree.ROOT)} ({len(want.splitlines())} lines)")
	return 0


if __name__ == "__main__":
	sys.exit(main())
