app_name = "onedesk"
app_title = "One"
app_publisher = "One"
app_description = "Every One product, as modules on the Frappe desk"
app_email = "hello@4dl.app"
app_license = "agpl-3.0"
app_logo_url = "/assets/onedesk/images/one.svg"

# The site wears One from its first boot and carries nobody else's navbar rows or
# checklists; after that all of it is the tenant's, in Website and Navbar Settings.
after_install = ["onedesk.one.brand.apply", "onedesk.one.declutter.apply"]
extend_bootinfo = "onedesk.one.boot.boot_session"

# The One marks, as sprite symbols every Icon field can name.
# Generated by `scripts/icons.py`; the ids inside each one are rewritten so two
# marks in one sprite do not share a gradient.
fixtures = ["Custom Icon"]

add_to_apps_screen = [
	{
		"name": app_name,
		"title": app_title,
		"logo": app_logo_url,
		"route": "/desk/one",
		# Ahead of erpnext (1) and hrms (2). Not 0: the boot reads this with `or`,
		# so a falsy one falls through to the default and lands One mid-row.
		"sequence_id": 0.5,
	}
]

# `setup_wizard_url` is ignored while erpnext or hrms are installed.
setup_wizard_requires = "assets/onedesk/js/setup_wizard.js"
setup_wizard_stages = "onedesk.one.setup_wizard.get_setup_stages"

app_include_css = ["/assets/onedesk/css/theme.css", "/assets/onedesk/css/desk.css"]
app_include_js = ["/assets/onedesk/js/theme.js", "/assets/onedesk/js/desk.js"]
