app_name = "onedesk"
app_title = "One"
app_publisher = "One"
app_description = "Every One product, as modules on the Frappe desk"
app_email = "hello@4dl.app"
app_license = "agpl-3.0"
app_logo_url = "/assets/onedesk/images/one.svg"

# The site wears One from its first boot and carries nobody else's navbar rows or
# checklists; after that all of it is the tenant's, in Website and Navbar Settings.
after_install = [
	"onedesk.one_hr.policy.seed",
	"onedesk.one.brand.apply",
	"onedesk.one.declutter.apply",
	"onedesk.one.companions.apply",
]

# Their dock files do not carry the mount, so a newer erpnext or hrms clears it.
after_migrate = ["onedesk.one.companions.apply", "onedesk.one_hr.policy.seed"]
extend_bootinfo = "onedesk.one.boot.boot_session"

# A pattern is not visible from inside one request. See one_hr/healing.py.
scheduler_events = {
	"daily": ["onedesk.one_hr.healing.nightly"],
	"hourly": ["onedesk.one_hr.closing.hourly"],
}

# The One marks, as sprite symbols every Icon field can name. Generated by
# `scripts/icons.py`, with each one's ids rewritten so two marks in one sprite
# do not share a gradient.
# The marks, and the four reasons a day pauses. A workspace adds its own.
fixtures = ["Custom Icon", "Clock Reason"]

# A record answers before it offers links; see `onedesk/one_hr/employee.py`.
doctype_js = {"Employee": "public/js/employee.js"}

# Every shift location counts, not the first. See one_hr/checkin.py.
override_doctype_class = {"Employee Checkin": "onedesk.one_hr.checkin.OneEmployeeCheckin"}

add_to_apps_screen = [
	{
		"name": app_name,
		"title": app_title,
		"logo": app_logo_url,
		"route": "/desk/one",
		# Ahead of erpnext (1) and hrms (2). Not 0: the boot reads this with `or`,
		# so a falsy one falls through to the default and lands One mid-row.
		"sequence_id": 0.5,
	}
]

# `setup_wizard_url` is ignored while erpnext or hrms are installed.
# Reaches the login page: base.html renders these and login.html extends it.
web_include_js = ["/assets/onedesk/js/login.js"]

setup_wizard_requires = "assets/onedesk/js/setup_wizard.js"
setup_wizard_stages = "onedesk.one.setup_wizard.get_setup_stages"

app_include_css = ["/assets/onedesk/css/theme.css", "/assets/onedesk/css/desk.css"]
app_include_js = [
	"/assets/onedesk/js/theme.js",
	"/assets/onedesk/js/desk.js",
	"/assets/onedesk/js/passkey.js",
	"/assets/onedesk/js/clock.js",
]
